allowBuilds:
    esbuild: false
    lmdb: false
    msgpackr-extract: false

catalog:
    oxfmt: 0.67.0
    oxlint: 1.82.0
    vite: npm:@voidzero-dev/vite-plus-core@0.3.2
    vite-plus: 0.3.2
    vitest: 5.0.0

minimumReleaseAge: 0

overrides:
    oxfmt: 'catalog:'
    oxlint: 'catalog:'
    vite@*: 'catalog:'
    vitest@*: 'catalog:'

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'
