allowBuilds:
    esbuild: false
    lmdb: false
    msgpackr-extract: false

catalog:
    oxfmt: 0.68.0
    oxlint: 1.83.0
    vite: npm:@voidzero-dev/vite-plus-core@0.3.3
    vite-plus: 0.3.3
    vitest: 5.0.1

minimumReleaseAge: 0

overrides:
    oxfmt: 'catalog:'
    oxlint: 'catalog:'
    vite@*: 'catalog:'
    vitest@*: 'catalog:'

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'
